spring.application.name=spring-redis-crud-api

#Embadded Port Number
server.port=5656

#DataBase Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/redis_app
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Som@123#


# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Chaching Entries
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379